import { Rule } from '@/types';

export const rules: Rule[] = [
  {
    tag: 'low',
    id: 'rl1',
    resort: 'roza',
    title: 'Низкий сезон',
    subtitle: ''
  },
  {
    tag: 'peak',
    id: 'rp1',
    resort: 'roza',
    title: 'Пик',
    subtitle: 'с 29 декабря',
  },
  {
    tag: 'low',
    id: 'rl2',
    resort: 'roza',
    title: 'Низкий сезон',
    subtitle: 'с 9 января',
  },
  {
    tag: 'high',
    id: 'rh1',
    resort: 'roza',
    title: 'Высокий сезон',
    subtitle: 'с 28 января',
  },
  {
    tag: 'peak',
    id: 'rp2',
    resort: 'roza',
    title: 'Пик',
    subtitle: 'с 11 февраля',
  },
  {
    tag: 'high',
    id: 'rh2',
    resort: 'roza',
    title: 'Высокий сезон',
    subtitle: 'с 27 февраля',
  },
  {
    tag: 'low',
    id: 'rl3',
    resort: 'roza',
    title: 'Низкий сезон',
    subtitle: 'с 13 марта',
  },
  {
    tag: 'low',
    id: 'kl1',
    resort: 'kp',
    title: 'Низкий сезон',
  },
  {
    tag: 'peak',
    id: 'kp1',
    resort: 'kp',
    title: 'Пик',
    subtitle: 'с 24 декабря',
  },
  {
    tag: 'high',
    id: 'kh1',
    resort: 'kp',
    title: 'Высокий сезон',
    subtitle: 'с 9 января',
  },
  {
    tag: 'peak',
    id: 'kp2',
    resort: 'kp',
    title: 'Пик',
    subtitle: 'с 1 февраля',
  },
  {
    tag: 'high',
    id: 'kh2',
    resort: 'kp',
    title: 'Высокий сезон',
    subtitle: 'с 13 марта',
  },
  {
    tag: 'low',
    id: 'kl2',
    resort: 'kp',
    title: 'Низкий сезон',
    subtitle: 'с 1 апреля',
  },
  {
    tag: 'low',
    id: 'gb',
    resort: 'gazprom',
    title: 'Будни',
    subtitle: 'пн-чт',
  },
  {
    tag: 'high',
    id: 'gv',
    resort: 'gazprom',
    title: 'Выходные',
    subtitle: 'пт-вс',
  },
  {
    tag: 'peak',
    id: 'gp1',
    resort: 'gazprom',
    title: 'Праздники',
    subtitle: '24 декабря – 08января',
  },
  {
    tag: 'peak',
    id: 'gp2',
    resort: 'gazprom',
    title: '',
    subtitle: '22-26 февраля',
  },
  {
    tag: 'peak',
    id: 'gp3',
    resort: 'gazprom',
    title: '',
    subtitle: '7-8 марта',
  },
];
